# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 11:37
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'care_course',
            },
        ),
        migrations.CreateModel(
            name='CourseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.TimeField()),
            ],
            options={
                'db_table': 'care_course_item',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('program_label', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[], size=None)),
                ('response_labels', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('response_values', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'care_question',
            },
        ),
        migrations.AddField(
            model_name='courseitem',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care.Question'),
        ),
        migrations.AddField(
            model_name='courseitem',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care.Course'),
        ),
    ]
