# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-16 02:49
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0003_auto_20171003_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='program_label',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='question',
            name='response_labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='question',
            name='response_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None),
        ),
    ]
