# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-12 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0005_course_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='report',
            field=models.CharField(blank=True, choices=[('comp-1', '陪伴回報表'), ('care-1', '照護回報表')], max_length=500, null=True),
        ),
    ]
