# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0006_auto_20171112_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='report',
            field=models.CharField(blank=True, choices=[('care-1', '照護回報表'), ('comp-1', '陪伴回報表')], max_length=500, null=True),
        ),
    ]
