# Generated by Django 2.0 on 2017-12-16 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0007_auto_20171130_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursequestion',
            name='question',
            field=models.ForeignKey(limit_choices_to={'archived': False}, on_delete=django.db.models.deletion.CASCADE, to='care.Question'),
        ),
    ]
