# Generated by Django 2.0 on 2017-12-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0008_auto_20171216_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='report',
            field=models.CharField(blank=True, choices=[('comp-1', '陪伴回報表'), ('care-1', '照護回報表')], max_length=500, null=True),
        ),
    ]
