# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 08:54
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineBotIntegration',
            fields=[
                ('lineid', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'customer_linebot_integration',
            },
        ),
        migrations.CreateModel(
            name='MessageQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('message', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'customer_message_queue',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phone', models.TextField(null=True)),
                ('profile', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.AddField(
            model_name='messagequeue',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Profile'),
        ),
        migrations.AddField(
            model_name='linebotintegration',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Profile'),
        ),
    ]
