# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-29 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20171019_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linemessagequeue',
            name='message',
            field=models.TextField(),
        ),
    ]
