# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 11:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('care', '0001_initial'),
        ('employee', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_int', models.IntegerField(null=True)),
                ('answer_str', models.TextField(null=True)),
                ('routine', models.BooleanField()),
                ('scheduled_at', models.DateField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'patient_care_history',
            },
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_mask', models.IntegerField()),
            ],
            options={
                'db_table': 'patient_course_table',
            },
        ),
        migrations.CreateModel(
            name='GlobalVariable',
            fields=[
                ('key', models.TextField(primary_key=True, serialize=False)),
                ('value', models.TextField(null=True)),
            ],
            options={
                'db_table': 'global_variable',
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.TextField(null=True)),
            ],
            options={
                'db_table': 'patient_guardian',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'patient_manager',
            },
        ),
        migrations.CreateModel(
            name='NursingSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('flow_control', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'patient_nursing_schedule',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('birthday', models.DateField(null=True)),
                ('extend', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'patient_profile',
            },
        ),
        migrations.CreateModel(
            name='SpecialCourseSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Profile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_course_schedule', to='patient.Profile')),
            ],
            options={
                'db_table': 'patient_special_course_table',
            },
        ),
        migrations.AddField(
            model_name='nursingschedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_schedule', to='employee.Profile'),
        ),
        migrations.AddField(
            model_name='nursingschedule',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='patient.Profile'),
        ),
        migrations.AddField(
            model_name='manager',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Profile'),
        ),
        migrations.AddField(
            model_name='manager',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Profile'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Profile'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Profile'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_schedule', to='patient.Profile'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care.Course'),
        ),
        migrations.AddField(
            model_name='carehistory',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employee.Profile'),
        ),
        migrations.AddField(
            model_name='carehistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Profile'),
        ),
        migrations.AddField(
            model_name='carehistory',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care.Question'),
        ),
    ]
