# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-21 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20170921_0050'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='caredairlyreport',
            unique_together=set([('patient', 'report_date', 'report_period')]),
        ),
    ]
