# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-24 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('customer', '0001_initial'),
        ('patient', '0004_delete_globalvariable'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='relation',
            field=models.TextField(default='照護經理'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='guardian',
            unique_together=set([('patient', 'customer')]),
        ),
        migrations.AlterUniqueTogether(
            name='manager',
            unique_together=set([('patient', 'employee')]),
        ),
    ]
