# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-03 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20170924_2017'),
        ('employee', '0001_initial'),
        ('patient', '0005_auto_20170924_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='customers',
            field=models.ManyToManyField(related_name='patients', through='patient.Guardian', to='customer.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='managers',
            field=models.ManyToManyField(related_name='patients', through='patient.Manager', to='employee.Profile'),
        ),
    ]
