# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-16 03:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20171003_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialcourseschedule',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='specialcourseschedule',
            name='patient',
        ),
        migrations.DeleteModel(
            name='SpecialCourseSchedule',
        ),
    ]
