# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-27 08:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_auto_20171019_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='UkumpGlobal',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('value', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'ukump_global',
            },
        ),
    ]
