# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_auto_20171031_1418'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='caredairlyreport',
            table='patient_daily_report',
        ),
    ]
