# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_auto_20171031_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='caredailyreport',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
