# Generated by Django 2.0 on 2017-12-18 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_guardian_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinebotDummyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineid', models.TextField()),
                ('catalog', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Profile')),
            ],
            options={
                'db_table': 'linebot_dummy_log',
            },
        ),
    ]
