# Generated by Django 2.0 on 2017-12-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0018_linebotdummylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linebotdummylog',
            name='payload',
            field=models.TextField(),
        ),
    ]
